### ISSUE TITLE
Club Listings

### ISSUE THREAD

**Issue by F22RaptorStrike** [MWHSCSC-ORG/westwildcats#2]
Mr. Young suggests that we shrink down the club boxes and pictures so we can fit more clubs per page. Most likely from 6 clubs a page to  8-10 clubs a page.

Files affected:
* page1.html
* page2.html
* page3.html
* page4.html
* page5.html
* page6.html

Would require extensive CSS reformatting.

**Comment by dbradley771** [comment]
I don't why we couldn't just put them all on the same screen.

**Comment by F22RaptorStrike** [comment]
It might lead to a lack of content  / picture size for clubs. I don't know for sure.

**Comment by F22RaptorStrike** [comment]
Do we want to shrink the size of the club boxes so we can fit them all or do we just want to have them all the size they are now, just on one big scrolling page?

**Comment by dbradley771** [comment]
Could we do three per column and just extend the page to fit them all?
Maybe we can and alphabetical dividers with quick links at the top so you can jump to a section.
